name: ci

on:
  push:
    branches:
      - "**"

jobs:
  lint-typecheck-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9.9
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - run: pnpm i --frozen-lockfile
      - run: pnpm lint
      - run: pnpm check-types
      - run: pnpm build
